# Titles and information
title: "Koen Westendorp"
tagline: "This is a barebones template"

# Files
sass:
    sass_dir: css
exclude: [.sass, README.md]

# Linking
permalinks: /:year/:month/:day/:title
####url: "http://yourwebsite.com"

# Social
twitter: "Koen__W"
github: "KoenWestendorp"
youtube: "UCFu7dWFlfRxkTX1kpBSpNAg"
dribbble: "KoenWestendorp"
